apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: check-website
spec:
  params:
    - name: website
      type: string
  steps:
    - name: banner
      image: alpine
      script: |
        #!/bin/sh
        echo "---------------------------------------------"
        echo "Checking service $(params.website)"
        echo "---------------------------------------------"
    - name: docker-hello
      image: docker.io/hello-world
    - name: check
      image: alpine
      script: |
        nslookup $(params.website)
        ping -c 3 $(params.website)
