# Example: A Task that checks connectivity to Red Hat
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: check-redhat
spec:
  steps:
    - name: nslookup
      image: alpine
      script: |
        nslookup www.redhat.com

    - name: ping
      image: alpine
      script: |
        ping -c 3 www.redhat.com
