# Example: A Pipeline that executes the explicit Tasks that check hardcoded websites
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-check-websites
spec:
  tasks:
    - name: google
      taskRef:
        name: check-google

    - name: redhat
      runAfter:
        - google
      taskRef:
        name: check-redhat