apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-check-websites
spec:
  tasks:
    - name: google
      taskRef:
        name: check-google
    - name: yahoo
      runAfter:
        - google
      taskRef:
        name: check-yahoo