# Example: A Pipeline that takes a list of 'websites' and invokes the parameterized Task (check-website)
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-check-services
spec:
  params:
    - name: websites
      type: array
      description: List of website services to check
      default:
        - www.google.com
        - www.redhat.com
    - name: namespace
      type: string
      description: The namespace of the provided website(s)
      default: "00000"
    - name: scenarioId
      type: string
      description: Identifier for the test scenario
      default: "00000"

  tasks:
    - name: init-scenario
      taskSpec:
        params:
          - name: scenarioId
            type: string
        steps:
          - name:
            image: alpine
            script: |
              #!/bin/sh
              echo "---------------------------------------------"
              echo "Checking services: $(params.scenarioId)"
              echo "Namespace: $(params.namespace)"
              echo "---------------------------------------------"
      params:
        - name: scenarioId
          value: $(params.scenarioId)

    - name: check-service
      taskRef:
        name: check-website
      matrix:
        params:
          - name: website
            value: $(params.websites[*])
