apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pipeline-check-services
spec:
  pipelineRef:
    name: pipeline-check-services
  params:
    - name: websites
      value:
        - www.google.com
        - www.redhat.com
        - www.caci.com
