# EventListener for pipeline-check-websites.
# Exposes an HTTP webhook endpoint. A POST to the listener service triggers
# a new PipelineRun via the TriggerTemplate.
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: scenario-check-services-listener
spec:
  serviceAccountName: tekton-robot
  triggers:
    - name: scenario-check-services
      bindings:
        - ref: scenario-check-services-parameters
      template:
        ref: scenario-check-services-template
